---
title: "Application results"
author: "Nutcha Wattanachit, Evan L. Ray, Thomas C. McAndrew, Nicholas G. Reich"
header-includes:
   - \usepackage{amsmath}
   - \usepackage{tabularx}
   - \usepackage{hyperref}
   - \usepackage{multicol}
   - \usepackage{longtable}
   - \usepackage{array}
   - \usepackage{multirow}
   - \usepackage{wrapfig}
   - \usepackage{float}
   - \usepackage{colortbl}
   - \usepackage{pdflscape}
   - \usepackage{booktabs}
   - \usepackage{tabu}
   - \usepackage{threeparttable}
   - \usepackage{threeparttablex}
   - \usepackage{makecell}
   - \usepackage{xcolor}
output:
  pdf_document:
        keep_tex: false
        latex_engine: xelatex
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(gridExtra)
library(grid)
library(scales)
library(cdcfluview)
library(RColorBrewer)
library(ggpubr)
knitr::opts_chunk$set(echo = FALSE,fig.pos = "H",fig.retina=2)
```

# Log scores

```{r}
path <- getwd()
seasons <- c("2010/2011","2011/2012","2012/2013","2013/2014","2014/2015","2015/2016",
             "2016/2017","2017/2018","2018/2019")
test_s <- seasons[7:9]
tars  <- sapply(1:4, function(x) paste0(x," wk ahead"))
source(paste0(path,"/BLPwork_functions_app/tables_plots_functions.R"))
source(paste0(path,"/BLPwork_functions_app/functions_app.R"))
## get data
cv_scores1_all <- read.csv(paste0(path,"/ensembles/pit_ls_frame/cv/tables/sea17.csv")) %>%
  dplyr::group_by(model_name,target) %>%
  dplyr::mutate(mtls=mean(mean_ls_train),
                mtest=mean(mean_ls_valid))%>%
  dplyr::ungroup() %>%
  dplyr::mutate(ew_logi=ifelse(grepl("EW_BMC",model_name),1,0)) %>%
  group_by(ew_logi,target) %>%
  dplyr::mutate(group_sd1=sd(mtest),
                cutoff=max(mtest)-group_sd1,
                max_model=model_name[which.max(mtest)]) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(target,ew_logi) %>%
  dplyr::mutate(rank=rank(-round(mtest,2), ties.method="min")) %>%
  ungroup() %>%
  dplyr::select(-"mean_ls_train",-"mean_ls_valid",-"valids",-"valid_season",-"ew_logi") %>%
  dplyr::arrange(target) %>%
  distinct() 

cv_scores1_select <- read.csv(paste0(path,"/ensembles/pit_ls_frame/cv/tables/sea17.csv")) %>%
  dplyr::group_by(model_name,target) %>%
  dplyr::mutate(mtls=mean(mean_ls_train),
                mtest=mean(mean_ls_valid))%>%
  dplyr::ungroup() %>%
  dplyr::mutate(ew_logi=ifelse(grepl("EW_BMC",model_name),1,0)) %>%
  group_by(ew_logi,target) %>%
  dplyr::mutate(group_sd1=sd(mtest),
                cutoff=max(mtest)-group_sd1,
                max_model=model_name[which.max(mtest)],
                comp=substr(model_name, nchar(model_name), nchar(model_name)))%>%
  dplyr::filter(round(mtest,2)>=round(cutoff,2)) %>%
  dplyr::mutate(select_model=model_name[which.min(as.numeric(comp))]) %>%
  dplyr::filter(select_model==model_name) %>%
  dplyr::ungroup() %>%
  dplyr::select(-"mean_ls_train",-"mean_ls_valid",-"valids",-"valid_season",-"mtls",-"ew_logi",-"comp") %>%
  dplyr::arrange(target) %>%
  dplyr::distinct()

cv_scores2_all <- read.csv(paste0(path,"/ensembles/pit_ls_frame/cv/tables/sea18.csv")) %>%
  dplyr::group_by(model_name,target) %>%
  dplyr::mutate(mtls=mean(mean_ls_train),
                mtest=mean(mean_ls_valid))%>%
  dplyr::ungroup() %>%
  dplyr::mutate(ew_logi=ifelse(grepl("EW_BMC",model_name),1,0)) %>%
  group_by(ew_logi,target) %>%
  dplyr::mutate(group_sd1=sd(mtest),
                cutoff=max(mtest)-group_sd1,
                max_model=model_name[which.max(mtest)])%>%
  dplyr::ungroup() %>%
  dplyr::group_by(target,ew_logi) %>%
  dplyr::mutate(rank=rank(-round(mtest,2), ties.method="min")) %>%
  ungroup() %>%
  dplyr::select(-"mean_ls_train",-"mean_ls_valid",-"valids",-"valid_season",-"ew_logi") %>%
  dplyr::arrange(target) %>%
  distinct()

cv_scores2_select <- read.csv(paste0(path,"/ensembles/pit_ls_frame/cv/tables/sea18.csv")) %>%
  dplyr::group_by(model_name,target) %>%
  dplyr::mutate(mtls=mean(mean_ls_train),
                mtest=mean(mean_ls_valid))%>%
  dplyr::ungroup() %>%
  dplyr::mutate(ew_logi=ifelse(grepl("EW_BMC",model_name),1,0)) %>%
  group_by(ew_logi,target) %>%
  dplyr::mutate(group_sd1=sd(mtest),
                cutoff=max(mtest)-group_sd1,
                max_model=model_name[which.max(mtest)],
                comp=substr(model_name, nchar(model_name), nchar(model_name)))%>%
  dplyr::filter(round(mtest,2)>=round(cutoff,2)) %>%
  dplyr::mutate(select_model=model_name[which.min(as.numeric(comp))]) %>%
  dplyr::filter(select_model==model_name) %>%
  dplyr::ungroup() %>%
  dplyr::select(-"mean_ls_train",-"mean_ls_valid",-"valids",-"valid_season",-"mtls",-"ew_logi",-"comp") %>%
  dplyr::arrange(target) %>%
  dplyr::distinct()

cv_scores3_all <- read.csv(paste0(path,"/ensembles/pit_ls_frame/cv/tables/sea19.csv")) %>%
  dplyr::group_by(model_name,target) %>%
  dplyr::mutate(mtls=mean(mean_ls_train),
                mtest=mean(mean_ls_valid))%>%
  dplyr::ungroup() %>%
  dplyr::mutate(ew_logi=ifelse(grepl("EW_BMC",model_name),1,0)) %>%
  group_by(ew_logi,target) %>%
  dplyr::mutate(group_sd1=sd(mtest),
                cutoff=max(mtest)-group_sd1,
                max_model=model_name[which.max(mtest)])%>%
  dplyr::ungroup() %>%
  dplyr::group_by(target,ew_logi) %>%
  dplyr::mutate(rank=rank(-round(mtest,2), ties.method="min")) %>%
  ungroup() %>%
  dplyr::select(-"mean_ls_train",-"mean_ls_valid",-"valids",-"valid_season",-"ew_logi") %>%
  dplyr::arrange(target) %>%
  distinct()

cv_scores3_select <- read.csv(paste0(path,"/ensembles/pit_ls_frame/cv/tables/sea19.csv")) %>%
  dplyr::group_by(model_name,target) %>%
  dplyr::mutate(mtls=mean(mean_ls_train),
                mtest=mean(mean_ls_valid))%>%
  dplyr::ungroup() %>%
  dplyr::mutate(ew_logi=ifelse(grepl("EW_BMC",model_name),1,0)) %>%
  group_by(ew_logi,target) %>%
  dplyr::mutate(group_sd1=sd(mtest),
                cutoff=max(mtest)-group_sd1,
                max_model=model_name[which.max(mtest)],
                comp=substr(model_name, nchar(model_name), nchar(model_name)))%>%
  dplyr::filter(round(mtest,2)>=round(cutoff,2)) %>%
  dplyr::mutate(select_model=model_name[which.min(as.numeric(comp))]) %>%
  dplyr::filter(select_model==model_name) %>%
  dplyr::ungroup() %>%
  dplyr::select(-"mean_ls_train",-"mean_ls_valid",-"valids",-"valid_season",-"mtls",-"ew_logi",-"comp") %>%
  dplyr::arrange(target) %>%
  dplyr::distinct()

cv_scores1 <- cv_scores1_all[,c(1:4,8)] 
cv_scores2 <- cv_scores2_all[,c(1:4,8)]
cv_scores3 <- cv_scores3_all[,c(1:4,8)] 

colnames(cv_scores1) <- c("Target","Model Name","Mean train log score","Mean validation log score","rank")
colnames(cv_scores2) <- c("Target","Model Name","Mean train log score","Mean validation log score","rank")
colnames(cv_scores3) <- c("Target","Model Name","Mean train log score","Mean validation log score","rank")
```

```{r}
cv_scores1t <- cv_scores1 %>%
  dplyr::select(-c("rank", "Mean train log score")) %>%
  pivot_wider(names_from ="Model Name", values_from="Mean validation log score")
cv_scores2t <- cv_scores2 %>%
  dplyr::select(-c("rank", "Mean train log score")) %>%
  pivot_wider(names_from ="Model Name", values_from="Mean validation log score")
cv_scores3t <- cv_scores3 %>%
  dplyr::select(-c("rank", "Mean train log score")) %>%
  pivot_wider(names_from ="Model Name", values_from="Mean validation log score")
```

```{r cvtabs,fig.width=4}
knitr::kable(cv_scores1t,digits=2)
knitr::kable(cv_scores2t,digits=2)
knitr::kable(cv_scores3t,digits=2)
```

## Mean train and test log scores

```{r}
## get data
final_ls1 <- read.csv(paste0(path,"/ensembles/pit_ls_frame/train_test/ls_fsn_frame.csv")) 
final_ls2  <- read.csv(paste0(path,"/ensembles/pit_ls_frame/train_test/ls_tw_frame.csv")) %>%
  dplyr::filter(!is.na(mean_ls_test)) 
final_ls <- rbind(final_ls1,final_ls2)

## build detailed log scores
for(i in 17:19){
  p1 <-paste0(path,"/ensembles/pit_ls_frame/train_test/",i) 
  p2 <-paste0(path,"/ensembles/pit_ls_frame/train_test/EW_TLP/",i)
  ls1 <- map_dfr(1:4, function(j) {
    read.csv(paste0(p1,"/target",j,".csv"))}) %>%
      dplyr::mutate(ls=replace(ls, ls < -10, -10))
  ls2 <- map_dfr(1:4, function(j) {
    read.csv(paste0(p2,"/target",j,".csv")) %>%
      dplyr::mutate(ls=replace(ls, ls < -10, -10))
    })
  assign(paste0("locls",i), rbind(ls1,ls2))
}
## build location log scores by location for test 
for(i in 17:19){
  seas <- ifelse(i==17,"2016/2017",ifelse(i==18,"2017/2018","2018/2019"))
  assign(paste0("ploc",i), 
         get(paste0("locls",i)) %>%
           dplyr::filter(season==seas,
                         !(model_name %in% c("EW_BMC5","EW_BMC3"))) %>%
           dplyr::group_by(location,target,model_name) %>%
           dplyr::mutate(loc_mean=mean(ls)) %>%
           ungroup() %>%
           dplyr::select(-c("bin_start_incl","bin_end_notincl","calendar_week",
                            "cdf_vals","value","ls","Valid.Bin_start_incl")) %>%
           distinct()
         )
}

# table
for(i in 1:3){
  final_ls2 <- final_ls %>%
    dplyr::filter(test_season==test_s[i]) %>%
    dplyr::arrange(target) %>%
    pivot_longer(
      cols =c("mean_ls_train","mean_ls_test"),
      values_to = "value") %>%
    dplyr::mutate(test_train=ifelse(name=="mean_ls_train",
                                    paste0("training period\n average for \n",test_season),test_season)) %>%
    dplyr::select(-"name") %>%
    dplyr::arrange(target,test_train,desc(value)) %>%
    group_by(target,test_train) %>%
    dplyr::mutate(rank=rank(-round(value,2), ties.method="min")) %>%
    ungroup()
  colnames(final_ls2) <- c("Target","Model Name","Test Season","value","test_train","rank")
  assign(paste0("tab",i),final_ls2)
}
```

```{r lsheatloc}
pdf(paste0(path,"/figures/ls_heatloc1-1.pdf"), width = 9, height = 7)
loc_heatmap(ploc17)
dev.off()

pdf(paste0(path,"/figures/ls_heatloc2-1.pdf"), width = 9, height = 7)
loc_heatmap(ploc18)
dev.off()

pdf(paste0(path,"/figures/ls_heatloc3-1.pdf"), width = 9, height = 7)
loc_heatmap(ploc19)
dev.off()
```

```{r lsheat1, fig.height=10}
mheat1 <- mean_heat(tab1,"2016/2017")
mheat2 <- mean_heat(tab2,"2017/2018")
mheat3 <- mean_heat(tab3,"2018/2019")
lsheat1 <- ggarrange(
  mheat1, mheat2, mheat3, 
  common.legend = TRUE, legend = "bottom",
  nrow=3,ncol=1
  )
pdf(paste0(path,"/figures/ls_comb.pdf"), width = 9, height = 8)
print(lsheat1)
dev.off()
``` 

# Mean log scores across all targets by season

```{r}
alltar_tab <- rbind(tab1,tab2,tab3) %>%
  dplyr::select(`Model Name`, value, test_train,`Test Season`) %>%
  dplyr::mutate(test_train=ifelse(grepl("training period",test_train),
                                  "training period\n average","test period\n average")) %>%
  dplyr::group_by(test_train,`Model Name`,`Test Season`) %>%
  dplyr::mutate(mean_across=mean(value)) %>%
  dplyr::ungroup() %>%
  dplyr::select(-value) %>%
  dplyr::distinct() %>%
  dplyr::group_by(test_train,`Test Season`) %>%
  dplyr::mutate(rank=rank(-round(mean_across,2), ties.method="min")) %>%
  dplyr::ungroup()

# combine all tables
all_tab <- rbind(tab1,tab2,tab3) %>%
  dplyr::select(`Model Name`, value, test_train) %>%
  dplyr::mutate(test_train=ifelse(grepl("training period",test_train),
                                  "training period\n average","test period\n average")) %>%
  dplyr::group_by(test_train,`Model Name`) %>%
  dplyr::mutate(mean_across=mean(value)) %>%
  dplyr::ungroup() %>%
  dplyr::select(-value) %>%
  dplyr::distinct() %>%
  dplyr::group_by(test_train) %>%
  dplyr::mutate(rank=rank(-round(mean_across,2), ties.method="min")) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(`Test Season`="All seasons")
com_tab <- rbind(all_tab[,c(1:2,5,3:4)],alltar_tab)

# Mean log scores across all seasons by target
all_tab_sea <- rbind(tab1,tab2,tab3) %>%
  dplyr::select(`Model Name`, value, test_train,Target) %>%
  dplyr::mutate(test_train=ifelse(grepl("training period",test_train),
                                  "training period\n average","test period\n average")) %>%
  dplyr::group_by(test_train,`Model Name`,Target) %>%
  dplyr::mutate(mean_across=mean(value)) %>%
  dplyr::ungroup() %>%
  dplyr::select(-value) %>%
  dplyr::distinct() %>%
  dplyr::group_by(test_train,Target) %>%
  dplyr::mutate(rank=rank(-round(mean_across,2), ties.method="min")) %>%
  dplyr::ungroup()
```

```{r lsallyear,fig.height=6}
bottomm <-mean_heat_all2(com_tab,"(b) Mean log scores by season")
topm <- mean_heat_all3(all_tab_sea,"(a) Mean log scores by target")
main_ls <- ggarrange(
  topm, bottomm,
  common.legend = TRUE, legend = "bottom",
  nrow=2,ncol=1
  )
pdf(paste0(path,"/figures/logscore_main.pdf"), width = 9, height = 8)
print(main_ls)
dev.off()
``` 


# Box plot

```{r}
locls17 <- locls17 %>%
  dplyr::filter(season=="2016/2017") 
locls18 <- locls18 %>%
  dplyr::filter(season=="2017/2018") 
locls19 <- locls19 %>%
  dplyr::filter(season=="2018/2019") 

comdat <- rbind(locls17,locls18,locls19)
``` 

```{r box}
mod_order <- c("EW","TLP","EW_BLP","BLP","EW_BMC2","BMC2")
name <- c(expression("EW-LP"),expression("LP"),expression("EW-BLP"),expression("BLP"),
          expression("EW-BMC"[2]),expression("BMC"[2]))
my_colors <-brewer.pal(n = 3, name = "Dark2")
boxplot_ls <- ggplot(comdat,aes(factor(model_name,levels=mod_order),ls,color=season)) +
  geom_boxplot(outlier.size=0)+
  stat_summary(fun=mean,geom='point',shape=4,col='black',
               aes(group = season), position=position_dodge(.8),show.legend=TRUE)+
  facet_wrap(~target)+
  scale_color_manual(name="Season",values = my_colors) +
  scale_x_discrete(labels=name)+
  scale_shape_manual(values=c("Mean"="x"))+
  theme_bw()+
  ylab("Log scores")+
  xlab("Method")+
  theme(axis.text.x=element_text(size=7))
# save plot
pdf(paste0(path,"/figures/logscore_variations_boxplot.pdf"), width = 9, height = 8)
print(boxplot_ls)
dev.off()
``` 

# Probability plots

```{r}
set.seed(1234)
some_files1 <- list.files(paste0(path,"/ensembles/pit_ls_frame/train_test/",17,"/"),
                            full.names=TRUE, recursive = TRUE)
some_files2 <- list.files(paste0(path,"/ensembles/pit_ls_frame/train_test/EW_TLP/",17,"/"),
                            full.names=TRUE, recursive = TRUE)
some_files3 <- list.files(paste0(path,"/ensembles/pit_ls_frame/train_test/",18,"/"),
                            full.names=TRUE, recursive = TRUE)
some_files4 <- list.files(paste0(path,"/ensembles/pit_ls_frame/train_test/EW_TLP/",18,"/"),
                            full.names=TRUE, recursive = TRUE)
some_files5 <- list.files(paste0(path,"/ensembles/pit_ls_frame/train_test/",19,"/"),
                            full.names=TRUE, recursive = TRUE)
some_files6 <- list.files(paste0(path,"/ensembles/pit_ls_frame/train_test/EW_TLP/",19,"/"),
                            full.names=TRUE, recursive = TRUE)
```

## Test season 2016/2017
```{r}
cd_pplot <- function(cdtab1,cdtab2){
  cdtab1$tt <- "Training period"
  cdtab2$tt <- "Test period"
  cdtab <- rbind(cdtab1,cdtab2) %>%
    dplyr::mutate(tt=factor(tt, levels=c("Training period","Test period")))
  if("Season" %in% colnames(cdtab)){
    p <- ggplot(cdtab, aes(x=target,y=cd,color=Method))+
    geom_point() +
    facet_grid(Season~tt)+
    scale_colour_manual(
      values = c("#fdc086","#d95f02","#beaed4","#7570b3","#7fc97f","#1b9e77"),
      labels = parse_format())+
    ylab("Cramer Distance")+
    xlab("")+
    theme_bw()+
    theme(legend.position = "bottom",
          legend.text.align = 0) 
    
  } else {
    p <- ggplot(cdtab, aes(x=target,y=cd,color=Method))+
    geom_point() +
    facet_wrap(~tt)+
    scale_colour_manual(
      values = c("#fdc086","#d95f02","#beaed4","#7570b3","#7fc97f","#1b9e77"),
      labels = parse_format())+
    ylab("Cramer Distance")+
    xlab("")+
    theme_bw()+
    theme(legend.position = "bottom",
          legend.text.align = 0) 
  }
  print(p)
}
```

```{r reli1,fig.align="center",fig.pos='H'}
reli1p <- reli_plot(some_files1 ,some_files2,17,test=FALSE)
reli1pt <- reli_plot(some_files1 ,some_files2,17,test=TRUE)
tab1 <- reli_cd(some_files1,some_files2,17,test=FALSE,cd_type=2) %>%
  dplyr::mutate(Season="2016/2017")
tab2 <- reli_cd(some_files1,some_files2,17,test=TRUE,cd_type=2) %>%
  dplyr::mutate(Season="2016/2017")
knitr::kable(tab1)
knitr::kable(tab2)
```


## Test season 2017/2018

```{r reli2,fig.align="center",fig.pos='H'}
reli2p <- reli_plot(some_files3 ,some_files4,18,test=FALSE)
reli2pt <- reli_plot(some_files3 ,some_files4,18,test=TRUE)
tab3 <- reli_cd(some_files3,some_files4,18,test=FALSE,cd_type=2)%>%
  dplyr::mutate(Season="2017/2018")
tab4 <- reli_cd(some_files3,some_files4,18,test=TRUE,cd_type=2)%>%
  dplyr::mutate(Season="2017/2018")
knitr::kable(tab3)
knitr::kable(tab4)
```

## Test season 2018/2019

```{r reli3,fig.align="center",fig.pos='H'}
reli3p <- reli_plot(some_files5 ,some_files6,19,test=FALSE)
reli3pt <- reli_plot(some_files5 ,some_files6,19,test=TRUE)
tab5 <- reli_cd(some_files5,some_files6,19,test=FALSE,cd_type=2)%>%
  dplyr::mutate(Season="2018/2019")
tab6 <- reli_cd(some_files5,some_files6,19,test=TRUE,cd_type=2)%>%
  dplyr::mutate(Season="2018/2019")
knitr::kable(tab5)
knitr::kable(tab6)
```

```{r reli_sup_all,fig.align="center",fig.pos='H', fig.height=11,fig.width=8}
train_reli <- ggarrange(
  reli1p, reli2p, reli3p, 
  common.legend = TRUE, legend = "none",
  nrow=3,ncol=1
  )
test_reli <- ggarrange(
  reli1pt, reli2pt, reli3pt,
  common.legend = TRUE, legend = "none",
  nrow=3,ncol=1
  )

train_relip <- annotate_figure(train_reli, 
                              top = text_grob("Training period",face="bold"))
test_relip <- annotate_figure(test_reli, 
                              top = text_grob("Test period",face="bold"))

leg <- get_legend(reli1p)

reli_plot_all  <- ggarrange(
  train_relip, test_relip,
  legend.grob = leg,
  legend = "bottom",
  nrow=1,ncol=2
  )

pdf(paste0(path,"/figures/probplot_all.pdf"), width = 9, height = 13)
reli_plot_all
dev.off()
```

## Probability plot for all seasons by target

```{r reli4,fig.align="center",fig.pos='H', fig.height=5,fig.width=5}
reliall <- reli_plot2(some_files1 ,some_files2,some_files3 ,some_files4,some_files5 ,some_files6,test=FALSE)
reliallt <- reli_plot2(some_files1 ,some_files2,some_files3 ,some_files4,some_files5 ,some_files6,test=TRUE)
leg2 <- get_legend(reliall)
tab7 <- reli_cd2(some_files1 ,some_files2,some_files3 ,some_files4,some_files5 ,some_files6,test=FALSE,cd_type=2)
tab8 <- reli_cd2(some_files1 ,some_files2,some_files3 ,some_files4,some_files5 ,some_files6,test=TRUE,cd_type=2)
```

```{r reli_main,fig.align="center",fig.pos='H', fig.height=10,fig.width=8}
reliallp <- reliall
relialltp <- reliallt
ggarrange(
  reliallp, relialltp,
  common.legend = TRUE,
  legend = "right",
  nrow=2,ncol=1
  )

pdf(paste0(path,"/figures/probplot_main.pdf"), width = 7, height = 11)
ggarrange(
  reliallp, relialltp,
  common.legend = TRUE,
  legend = "right",
  nrow=2,ncol=1
  )
dev.off()
```

## Plot Cramer distances

```{r reli5,fig.align="center",fig.pos='H', fig.height=7,fig.width=9}
pdf(paste0(path,"/figures/cd_plot1.pdf"), width = 9, height = 7)
cd_pplot(tab7,tab8)
dev.off()
```


```{r reli6,fig.align="center",fig.pos='H', fig.height=11,fig.width=8}
tab9 <- rbind(tab1,tab3,tab5)
tab10 <-rbind(tab2,tab4,tab6)
pdf(paste0(path,"/figures/cd_plot2.pdf"), width = 8, height = 11)
cd_pplot(tab9,tab10)
dev.off()
```

## Plot Flu data

```{r}
library(FluSight)
ili_dat <- ilinet(region ="hhs", years = NULL) %>%
  dplyr::bind_rows(ilinet(region ="national", years = NULL)) %>%
  dplyr::mutate(Region=ifelse(region_type=="HHS Regions",paste0("HHS ",region),region)) %>%
  dplyr::filter(week_start >= "2010-08-25" & week_start <= "2019-06-30")
```


```{r}
library(lubridate)
ili_dat_epi <- ili_dat %>%
  dplyr::mutate(epiweek=as.numeric(week),
                week=ifelse(epiweek>20,(epiweek-40)+1,ifelse(lag(epiweek)==53,epiweek+14,epiweek+13)),
                Season=ifelse(epiweek<21, paste0(year-1,"/",year),paste0(year,"/",year+1)),
                ltype=ifelse(Season %in% c("2016/2017","2017/2018","2018/2019"), "a","b"))  %>%
  dplyr::filter(Region %in% c("National", paste0("HHS Region ", c(1,4,8,9))),
                !(epiweek %in% c(21:39))) 
# national plot
flu1 <- ili_dat_epi %>%
  dplyr::filter(Region =="National") %>% 
ggplot(.,aes(x=week,y=weighted_ili,color=Season))+
  geom_line(aes(linetype=ltype), show.legend = FALSE)+
  labs(x = "Epiweek", y = "Weighted ILI (%)")+
  scale_x_continuous(breaks=seq(2,32,2),
                     labels=c(c(2,4,6,8,10,12)+40,
                              c(14,16,18,20,22,24,26,28,30,32)-12),
                     limits = c(1, 33),
                     expand = expansion())+
  scale_color_brewer(palette="Paired") +
  scale_y_continuous(breaks=seq(0,10,1),limits = c(0, 10),labels=sprintf("%0.1f", round(seq(0,10,1), 1)))+
 guides(linetype = "none")+
  ggtitle("National")+
  theme_bw()+
  theme(text = element_text(size=10),
        axis.text.x = element_text(size=10),
        plot.margin=unit(c(0.2,0.1,0.1,0.4), "cm"))
flu2 <- ili_dat_epi %>%
  dplyr::filter(Region !="National") %>% 
ggplot(.,aes(x=week,y=weighted_ili,color=Season))+
  geom_line(aes(linetype=ltype))+
  facet_wrap(~Region) +
  labs(x = "Epiweek", y = "")+
  scale_x_continuous(breaks=seq(2,32,2),
                     labels=c(c(2,4,6,8,10,12)+40,
                              c(14,16,18,20,22,24,26,28,30,32)-12),
                     limits = c(1, 33),
                     expand = expansion())+
  scale_color_brewer(palette="Paired") +
  scale_y_continuous(breaks=seq(0,10,1),limits = c(0, 10),labels=sprintf("%0.1f", round(seq(0,10,1), 1)))+
 guides(linetype = "none")+
  theme_bw()+
  theme(text = element_text(size=10),
        axis.text.x = element_text(size=7),
        plot.margin=unit(c(0.3,0.2,0.1,-0.4), "cm"))
```

```{r fludat,fig.align="center",fig.pos='H', fig.height=5,fig.width=8.5}
pdf(paste0(path,"/figures/fludat.pdf"), width = 9, height = 5)
ggarrange(
  flu1, flu2,
  common.legend = TRUE,
  legend = "bottom",
  nrow=1,ncol=2
  )
dev.off()
```

## Beta transformation

```{r t1}
samples <- c(50, 70, 90)
data("faithful")
y <- faithful$waiting

mixt.deviance <- function(theta,y) {
  pi1    <- theta[1]
  pi2    <- 1 - pi1
  mu1    <- theta[2]
  mu2    <- theta[3]
  sigma1 <- theta[4]
  sigma2 <- theta[5]
  pdf <- pi1*dnorm(y,mu1,sigma1) + pi2*dnorm(y,mu2,sigma2)
  deviance <- -2*sum(log(pdf))
 return(deviance)
  }

r.nlm <- nlm(mixt.deviance,c(.25,52,82,10,10),y)
theta.est <- c(r.nlm$estimate[1], 1-r.nlm$estimate[1], r.nlm$estimate[2:5])
dmixt <- function(x,theta) {
  pi1 <- theta[1]
  pi2 <- theta[2]
  mu1 <- theta[3]
  mu2 <- theta[4]
  sigma1 <- theta[5]
  sigma2 <- theta[6]
  f1 <- dnorm(x,mu1,sigma1)
  f2 <- dnorm(x,mu2,sigma2)
  f <- pi1*f1 + pi2*f2
}

x <- (35:100)
pdf.mixt <- dmixt(x,theta.est)
ggplot(data=faithful) + 
  geom_line(data=data.frame(x,pdf.mixt), aes(x,pdf.mixt),size=0.5)+
  ylab("PDF")+
  xlab("X")+
  scale_y_continuous(limits = c(0, 0.06))+
  theme_bw()+
  theme(aspect.ratio=1)
```


```{r t2}
pmixt <- function(x,theta) {
  pi1 <- theta[1]
  pi2 <- theta[2]
  mu1 <- theta[3]
  mu2 <- theta[4]
  sigma1 <- theta[5]
  sigma2 <- theta[6]
  F1 <- pnorm(x,mu1,sigma1)
  F2 <- pnorm(x,mu2,sigma2)
  F  <- pi1*F1 + pi2*F2
  return(F)
}
cdf.mixt <- pmixt(x,theta.est)

ggplot(data=data.frame(x,cdf.mixt)) + 
  geom_line(aes(x,cdf.mixt),size=0.5) +
  ylab("CDF")+
  xlab("X")+
  theme_bw()+
  theme(aspect.ratio=1)
```

```{r t3}
cdf.beta <- pbeta(cdf.mixt, shape1=2, shape2=3, ncp = 0, lower.tail = TRUE, log.p = FALSE)

ggplot(data=data.frame(cdf.mixt,cdf.beta)) + 
  geom_line(aes(cdf.mixt,cdf.beta),size=0.5) +
  ylab("CDF")+
  xlab("LP CDF")+
  theme_bw()+
  theme(aspect.ratio=1)
```

```{r t4}
ggplot(data=data.frame(x,cdf.beta)) + 
  geom_line(aes(x,cdf.beta),size=0.5) +
  ylab("CDF")+
  xlab("X")+
  scale_y_continuous(position = "right")+
  theme_bw()+
  theme(aspect.ratio=1)

```

```{r t5}
db <- dbeta(cdf.mixt, shape1=2, shape2=3, ncp = 0, log = FALSE)
dm <- db*pdf.mixt
ggplot(data=data.frame(x,dm)) + 
  geom_line(aes(x,dm),size=0.5) +
  ylab("PDF")+
  xlab("X")+
  scale_y_continuous(limits = c(0, 0.06))+
  theme_bw()+
  theme(aspect.ratio=1)
```