---
title: "Comparison of Ensemble Calibration Methods"
author: "Nutcha Wattanachit"
date: "01/11/2021"
tables: yes
header-includes:
   - \usepackage{booktabs}
   - \usepackage{tabularx}
   - \usepackage{hyperref}
   - \usepackage{multicol}
   - \usepackage{longtable}
   - \usepackage{array}
   - \usepackage{multirow}
   - \usepackage{wrapfig}
   - \usepackage{float}
   - \usepackage{colortbl}
   - \usepackage{pdflscape}
   - \usepackage{tabu}
   - \usepackage{threeparttable}
   - \usepackage{threeparttablex}
   - \usepackage{makecell}
   - \usepackage{xcolor}
output:
  pdf_document:
        keep_tex: true
        latex_engine: xelatex
---

```{r setup, include=FALSE}
library(tidyverse);library(cdcfluview);library(Matrix)
library(cowplot);library(data.table);library(reshape2)
library(gridExtra);library(ranger);library(xtable)
library(here);library(stats);library(mixtools)
library(ggforce);library(grid);library(FluSight)
library(rmutil);library(R.utils);library(knitr)
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, comment = FALSE, message=FALSE, fig.show= 'hold')
```

# Flu Forecasting Application

```{r, echo=FALSE}
source("/Users/ahctun_woon/git/end-of-2018-2019/cdc-flusight-ensemble/BLPwork_functions_app/tables_plots_functions.R")
```

```{r}
# info
targets<-c("1 wk ahead","2 wk ahead","3 wk ahead","4 wk ahead")
model_list<-c("CU_EAKFC_SEIRS","CU_EAKFC_SIRS","CU_EKF_SEIRS","CU_EKF_SIRS","CU_RHF_SEIRS","CU_RHF_SIRS","CUBMA",
              "Delphi_BasisRegression","Delphi_EmpiricalFutures","Delphi_EmpiricalTrajectories", "Delphi_ExtendedDeltaDensity",
              "Delphi_MarkovianDeltaDensity", "Delphi_Uniform", "LANL_DBMplus", "Protea_Cheetah", "Protea_Kudu",
              "Protea_Springbok", "ReichLab_kcde", "ReichLab_kde", "ReichLab_sarima_seasonal_difference_FALSE",
              "ReichLab_sarima_seasonal_difference_TRUE", "target-based-weights")
componentModel_list<-model_list[-22]
model_list_sc<-c("CU-BMA","CU-EAKFC_SEIRS","CU-EAKFC_SIRS", "CU-EKF_SEIRS", "CU-EKF_SIRS", "CU-RHF_SEIRS", "CU-RHF_SIRS",
                 "Delphi-BasisRegression", "Delphi-EmpiricalFuture", "Delphi-EmpiricalTraj", "Delphi-DeltaDensity1",
                 "Delphi-DeltaDensity2", "Delphi-Uniform", "LANL-DBMplus", "Protea Analytics-Cheetah", "Protea Analytics-Kudu",
                 "Protea Analytics-Springbok", "ReichLab-KCDE", "ReichLab-KDE", "ReichLab-SARIMA1", "ReichLab-SARIMA2",
                 "FSNetwork-CW", "FSNetwork-EW", "FSNetwork-TRW", "FSNetwork-TW", "FSNetwork-TTW")
test_seasons<-c("2016/2017","2017/2018","2018/2019")
# get truths
truths<-read.csv('/Users/ahctun_woon/git/end-of-2018-2019/cdc-flusight-ensemble/scores/target-multivals_1819.csv') %>%
  dplyr::filter(Target %in% targets, Calendar.Week %in% c(43:53,1:18))
truths$Valid.Bin_start_incl<-as.numeric(as.character(truths$Valid.Bin_start_incl))
# set non-BMC ensemble names
nonBMC_ensembles <- c("TLP","EW","BLP","EW-BLP")
# set path
main_path <- "/Users/ahctun_woon/git/end-of-2018-2019/cdc-flusight-ensemble/BLPdata_app/ensemble_results/"
```

```{r,cache=TRUE}
for (ensemble in nonBMC_ensembles){
  if(ensemble=="EW-BLP") {
    ens_path <- paste0(main_path,"EW_BLP/")
  }
  else {
    ens_path <- paste0(main_path,ensemble,"/")
  }
  frame1<- read.csv(paste0(ens_path,"/params_mean_ls.csv"))
  frame1$model_name <- ensemble
  assign(paste0(ensemble,"_params_mean_ls"),frame1)
  frame2 <- NULL
  for (ts in test_seasons) {
    short_ts <- substr(ts, nchar(ts)-1, nchar(ts))
    for (tar in targets){
      tar_num <- substr(tar,1,1)
      sp_path <- paste0(ens_path,short_ts,"/t",tar_num)
      mean_ls_season <- read.csv(paste0(sp_path,"/params_mean_ls.csv"))
      mean_ls_season$target <- tar
      mean_ls_season$season <- ts
      pit_ls_season <- read.csv(paste0(sp_path,"/test_pit_ls_info.csv"))
      pit_ls_season$model_name <- ensemble
      rbind(frame2,pit_ls_season)->frame2
    }
  }
  assign(paste0(ensemble,"_test_pit_ls"),frame2)
}

# combine table
combined_PIT <- rbind(TLP_test_pit_ls,EW_test_pit_ls,BLP_test_pit_ls,`EW-BLP_test_pit_ls`)
combined_ls <- rbind(TLP_params_mean_ls[,(ncol(TLP_params_mean_ls)-4):ncol(TLP_params_mean_ls)],
                     EW_params_mean_ls[,(ncol(EW_params_mean_ls)-4):ncol(EW_params_mean_ls)],
                     BLP_params_mean_ls[,(ncol(BLP_params_mean_ls)-4):ncol(BLP_params_mean_ls)],
                     `EW-BLP_params_mean_ls`[,(ncol(`EW-BLP_params_mean_ls`)-4):ncol(`EW-BLP_params_mean_ls`)])
```

## Log Scores

### By target

```{r}
tar_ls <- combined_ls %>%
  dplyr::group_by(target,model_name) %>%
  dplyr::mutate(train_score=round(mean(mean_train_ls),3),
                test_score=round(mean(mean_test_ls),3)) %>%
  ungroup()
kable(unique(tar_ls[c(3,5:7)]))
```

### By season

```{r}
sea_ls <- combined_ls %>%
  dplyr::group_by(test_season,model_name) %>%
  dplyr::mutate(train_score=round(mean(mean_train_ls),3),
                test_score=round(mean(mean_test_ls),3)) %>%
  ungroup()
kable(unique(sea_ls[c(4,5:7)]))
```

## Calibration

### 1 week ahead - 2016/17

```{r}
pitplot(combined_PIT,targets[1],test_seasons[1])
```

### 1 week ahead - 2017/18

```{r}
pitplot(combined_PIT,targets[1],test_seasons[2])
```

### 2 week ahead - 2016/17

```{r}
pitplot(combined_PIT,targets[2],test_seasons[1])
```

### 2 week ahead - 2017/18

```{r}
pitplot(combined_PIT,targets[2],test_seasons[2])
```

### 3 week ahead - 2016/17

```{r}
pitplot(combined_PIT,targets[3],test_seasons[1])
```

### 3 week ahead - 2017/18

```{r}
pitplot(combined_PIT,targets[3],test_seasons[2])
```

### 4 week ahead - 2016/17

```{r}
pitplot(combined_PIT,targets[4],test_seasons[1])
```

### 4 week ahead - 2017/18

```{r}
pitplot(combined_PIT,targets[4],test_seasons[2])
```


<!-- ### 1 Week Ahead Calibration  -->

<!-- ```{r} -->
<!-- pitplot(combined_PIT,targets[1],train_season[1]) -->
<!-- pitplot(combined_PIT,targets[1],train_season[2]) -->
<!-- ``` -->

<!-- ### 2 Week Ahead Calibration  -->

<!-- ```{r} -->
<!-- pitplot(combined_PIT,targets[2],train_season[1]) -->
<!-- pitplot(combined_PIT,targets[2],train_season[2]) -->
<!-- ``` -->

<!-- ### 3 Week Ahead Calibration  -->

<!-- ```{r} -->
<!-- pitplot(combined_PIT,targets[3],train_season[1]) -->
<!-- pitplot(combined_PIT,targets[3],train_season[2]) -->
<!-- ``` -->

<!-- ### 4 Week Ahead Calibration  -->

<!-- ```{r} -->
<!-- pitplot(combined_PIT,targets[4],train_season[1]) -->
<!-- pitplot(combined_PIT,targets[4],train_season[2]) -->
<!-- ``` -->

<!-- ### Log Scores -->

<!-- #### 1 Week Ahead -->

<!-- ```{r} -->
<!-- LStable_target(combined_LS,targets[1]) -->
<!-- ``` -->

<!-- #### 2 Week Ahead -->

<!-- ```{r} -->
<!-- LStable_target(combined_LS,targets[2]) -->
<!-- ``` -->

<!-- #### 3 Week Ahead -->

<!-- ```{r} -->
<!-- LStable_target(combined_LS,targets[3]) -->
<!-- ``` -->

<!-- #### 4 Week Ahead -->

<!-- ```{r} -->
<!-- LStable_target(combined_LS,targets[4]) -->
<!-- ``` -->

<!-- #### Across All Targets -->

<!-- ```{r} -->
<!-- LStable(combined_LS) -->
<!-- ``` -->